const games = [
  {
    gameName: "Assassin’s Creed Shadows",
    price: 4899,
    rating: { value: 4.6, count: 25000 },
    description:
      "Embark on a dual-character journey through feudal Japan, alternating between a nimble shinobi and a powerful samurai. Master shadow warfare and honorable combat while navigating political intrigue in this visually stunning open-world epic featuring dynamic seasons and revolutionary stealth mechanics.",
    genres: ["Action-Adventure", "RPG"],
    platforms: ["PC", "PlayStation", "Xbox"],
    developer: "Ubisoft Quebec",
    publisher: "Ubisoft",
    releaseDate: new Date("2024-11-15"),
    imageURL: "/images/assassins-creed-shadows.png",
    isReleased: false,
  },
  {
    gameName: "33 Immortals",
    price: 1299,
    rating: { value: 4.2, count: 8500 },
    description:
      "Massively multiplayer rogue-lite where 33 players cooperate to escape divine punishment. Battle through procedurally generated purgatories with class-based combat and world-altering magic. Features permadeath mechanics and persistent progression across runs.",
    genres: ["Action", "Rogue-lite"],
    platforms: ["PC", "Xbox"],
    developer: "Thunder Lotus Games",
    publisher: "Thunder Lotus Games",
    releaseDate: new Date("2024-10-08"),
    imageURL: "/images/33-immortals.png",
    isReleased: false,
  },
  {
    gameName: "Split Fiction",
    price: 1999,
    rating: { value: 4.4, count: 3200 },
    description:
      "Narrative-driven thriller where choices create parallel timelines. Solve quantum puzzles that affect multiple realities simultaneously, with consequences that ripple across dimensions. Features full voice acting and a dynamic soundtrack reacting to player decisions.",
    genres: ["Adventure", "Puzzle"],
    platforms: ["PC", "PlayStation"],
    developer: "Narrative Games Co.",
    publisher: "Indie World Studios",
    releaseDate: new Date("2025-02-14"),
    imageURL: "/images/split-fiction.jpg",
    isReleased: false,
  },
  {
    gameName: "BeamNG.drive",
    price: 899,
    rating: { value: 4.8, count: 45000 },
    description:
      "Ultra-realistic soft-body physics simulator offering endless vehicular destruction and creative experimentation. Test cars, planes, and experimental vehicles in detailed sandbox environments with continuous updates and mod support.",
    genres: ["Simulation", "Racing"],
    platforms: ["PC"],
    developer: "BeamNG GmbH",
    publisher: "BeamNG GmbH",
    releaseDate: new Date("2015-05-29"),
    imageURL: "/images/beamng-drive.png",
    isReleased: true,
  },
  {
    gameName: "Black Myth: Wukong",
    price: 3999,
    rating: { value: 4.8, count: 18000 },
    description:
      "Souls-like action RPG based on Chinese mythology. Wield transforming weapons and mystical abilities against legendary creatures in breathtaking environments. Features challenging combat and deep lore from Journey to the West.",
    genres: ["Action-RPG", "Souls-like"],
    platforms: ["PC", "PlayStation"],
    developer: "Game Science",
    publisher: "Game Science",
    releaseDate: new Date("2024-08-20"),
    imageURL: "/images/black-myth-wukong.png",
    isReleased: false,
  },
  {
    gameName: "CarX Drift Racing Online",
    price: 1499,
    rating: { value: 4.5, count: 12000 },
    description:
      "Realistic drift racing simulator with authentic JDM car customization. Compete in global leaderboards and perfect your technique with advanced telemetry data. Regular seasonal events with exclusive cosmetic rewards.",
    genres: ["Racing", "Simulation"],
    platforms: ["PC", "PlayStation", "Xbox"],
    developer: "CarX Technologies",
    publisher: "CarX Technologies",
    releaseDate: new Date("2020-05-07"),
    imageURL: "/images/carx-drift.png",
    isReleased: true,
  },
  {
    gameName: "Call of Duty: Warzone",
    price: 0,
    rating: { value: 4.5, count: 850000 },
    description:
      "Free-to-play battle royale featuring 150-player matches and cross-platform progression. Experience cutting-edge gunplay with regular content updates and integration with premium COD titles.",
    genres: ["FPS", "Battle Royale"],
    platforms: ["PC", "PlayStation", "Xbox"],
    developer: "Infinity Ward",
    publisher: "Activision",
    releaseDate: new Date("2020-03-10"),
    imageURL: "/images/cod-warzone.jpg",
    isReleased: true,
  },
  {
    gameName: "Cyberpunk 2077",
    price: 3499,
    rating: { value: 4.0, count: 225000 },
    description:
      "Open-world RPG set in Night City - a dystopian metropolis of cyber-enhanced criminals and corporate warfare. Features multiple lifepaths, deep character customization, and branching narratives.",
    genres: ["RPG", "Cyberpunk"],
    platforms: ["PC", "PlayStation", "Xbox"],
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    releaseDate: new Date("2020-12-10"),
    imageURL: "/images/cyberpunk-2077.png",
    isReleased: true,
  },
  {
    gameName: "Dead by Daylight",
    price: 1499,
    rating: { value: 4.3, count: 98000 },
    description:
      "4v1 asymmetric horror game pitting survivors against iconic killers. Features cross-over characters from popular horror franchises and regular content updates.",
    genres: ["Horror", "Survival"],
    platforms: ["PC", "PlayStation", "Xbox"],
    developer: "Behaviour Interactive",
    publisher: "Behaviour Interactive",
    releaseDate: new Date("2016-06-14"),
    imageURL: "/images/dead-by-daylight.png",
    isReleased: true,
  },
  {
    gameName: "EA SPORTS™ WRC 24",
    price: 4499,
    rating: { value: 4.1, count: 4500 },
    description:
      "Official World Rally Championship simulator with authentic stages and vehicles. Features realistic damage modeling and dynamic weather systems affecting track conditions.",
    genres: ["Racing", "Simulation"],
    platforms: ["PC", "PlayStation", "Xbox"],
    developer: "Codemasters",
    publisher: "Electronic Arts",
    releaseDate: new Date("2024-11-01"),
    imageURL: "/images/wrc-24.png",
    isReleased: false,
  },
  {
    gameName: "EA SPORTS FC™ 25 Standard Edition",
    price: 4999,
    rating: { value: 4.6, count: 15000 },
    description:
      "Next-gen football simulation with HyperMotionV technology capturing real-player movements. Enhanced Ultimate Team mode and realistic stadium atmospheres.",
    genres: ["Sports", "Simulation"],
    platforms: ["PC", "PlayStation", "Xbox"],
    developer: "EA Vancouver",
    publisher: "Electronic Arts",
    releaseDate: new Date("2024-09-27"),
    imageURL: "/images/ea-fc-25.png",
    isReleased: false,
  },
  {
    gameName: "Farming Simulator 25",
    price: 2999,
    rating: { value: 4.4, count: 7500 },
    description:
      "Most advanced farming experience with new livestock mechanics and crop varieties. Manage your farm across diverse biomes with realistic economic systems.",
    genres: ["Simulation", "Management"],
    platforms: ["PC", "PlayStation", "Xbox"],
    developer: "GIANTS Software",
    publisher: "GIANTS Software",
    releaseDate: new Date("2024-11-22"),
    imageURL: "/images/farming-sim-25.png",
    isReleased: false,
  },
  {
    gameName: "FINAL FANTASY VII REBIRTH",
    price: 5499,
    rating: { value: 4.9, count: 35000 },
    description:
      "Second chapter in the FFVII Remake project expanding Cloud's journey beyond Midgar. Features revamped combat system and explorable open-world regions.",
    genres: ["JRPG", "Action"],
    platforms: ["PlayStation"],
    developer: "Square Enix",
    publisher: "Square Enix",
    releaseDate: new Date("2024-02-29"),
    imageURL: "/images/ff7-rebirth.png",
    isReleased: true,
  },
  {
    gameName: "Goat Simulator: Remastered",
    price: 799,
    rating: { value: 4.7, count: 45000 },
    description:
      "Chaotic sandbox rebuilt with next-gen physics. Cause mayhem as a hyper-agile goat with new abilities and expanded multiplayer modes.",
    genres: ["Sandbox", "Comedy"],
    platforms: ["PC", "PlayStation", "Xbox"],
    developer: "Coffee Stain North",
    publisher: "Coffee Stain Publishing",
    releaseDate: new Date("2023-11-17"),
    imageURL: "/images/goat-sim-remastered.png",
    isReleased: true,
  },
  {
    gameName: "God of War Ragnarök",
    price: 4999,
    rating: { value: 4.9, count: 125000 },
    description:
      "Epic conclusion to Kratos' Norse saga featuring new weapons and realms to explore. Cinematic storytelling combined with visceral combat against Norse deities.",
    genres: ["Action-Adventure", "Hack-n-Slash"],
    platforms: ["PlayStation"],
    developer: "Santa Monica Studio",
    publisher: "Sony Interactive Entertainment",
    releaseDate: new Date("2022-11-09"),
    imageURL: "/images/god-of-war-ragnarok.png",
    isReleased: true,
  },
  {
    gameName: "Grand Theft Auto V Enhanced",
    price: 2999,
    rating: { value: 4.7, count: 1500000 },
    description:
      "Definitive edition of Los Santos' criminal underworld with enhanced graphics and performance. Includes all current updates and community-created content.",
    genres: ["Action", "Open World"],
    platforms: ["PC", "PlayStation", "Xbox"],
    developer: "Rockstar North",
    publisher: "Rockstar Games",
    releaseDate: new Date("2022-03-15"),
    imageURL: "/images/gta5-enhanced.jpg",
    isReleased: true,
  },
  {
    gameName: "Jurassic World Evolution 2",
    price: 3499,
    rating: { value: 4.3, count: 22000 },
    description:
      "Build and manage dinosaur parks with new aquatic and flying reptiles. Features Chaos Theory mode recreating movie scenarios and enhanced guest management.",
    genres: ["Simulation", "Strategy"],
    platforms: ["PC", "PlayStation", "Xbox"],
    developer: "Frontier Developments",
    publisher: "Frontier Developments",
    releaseDate: new Date("2021-11-09"),
    imageURL: "/images/jurassic-world-2.png",
    isReleased: true,
  },
  {
    gameName: "Kingdom Come: Deliverance II",
    price: 4299,
    rating: { value: 4.5, count: 18000 },
    description:
      "Sequel to the acclaimed historical RPG featuring large-scale medieval battles. Enhanced combat system and deeper character development in 15th-century Bohemia.",
    genres: ["RPG", "Historical"],
    platforms: ["PC", "PlayStation", "Xbox"],
    developer: "Warhorse Studios",
    publisher: "Deep Silver",
    releaseDate: new Date("2024-12-05"),
    imageURL: "/images/kingdom-come-2.png",
    isReleased: false,
  },
  {
    gameName: "Orcs Must Die! Deathtrap",
    price: 1999,
    rating: { value: 4.4, count: 6500 },
    description:
      "Co-op tower defense with new elemental traps and hero classes. Defend against massive hordes in dynamic arenas with environmental hazards.",
    genres: ["Strategy", "Action"],
    platforms: ["PC", "Xbox"],
    developer: "Robot Entertainment",
    publisher: "Robot Entertainment",
    releaseDate: new Date("2024-07-18"),
    imageURL: "/images/orcs-must-die-deathtrap.png",
    isReleased: false,
  },
  {
    gameName: "PC Building Simulator 2",
    price: 1499,
    rating: { value: 4.6, count: 12000 },
    description:
      "Realistic PC assembly simulator with licensed components. Diagnose hardware issues, optimize builds, and compete in benchmarking challenges.",
    genres: ["Simulation", "Educational"],
    platforms: ["PC"],
    developer: "Spiral House",
    publisher: "Epic Games",
    releaseDate: new Date("2022-10-12"),
    imageURL: "/images/pc-builder-2.png",
    isReleased: true,
  },
  {
    gameName: "Red Dead Redemption 2",
    price: 3799,
    rating: { value: 4.8, count: 680000 },
    description:
      "Epic Western adventure following Arthur Morgan's journey with the Van der Linde gang. Features vast open world with dynamic encounters and deep honor system.",
    genres: ["Action", "Open World"],
    platforms: ["PC", "PlayStation", "Xbox"],
    developer: "Rockstar Studios",
    publisher: "Rockstar Games",
    releaseDate: new Date("2018-10-26"),
    imageURL: "/images/red-dead-2.png",
    isReleased: true,
  },
  {
    gameName: "SnowRunner",
    price: 2499,
    rating: { value: 4.5, count: 35000 },
    description:
      "Off-road trucking simulator challenging players to deliver cargo through extreme terrain. Dynamic mud physics and customizable vehicles with upgrade systems.",
    genres: ["Simulation", "Driving"],
    platforms: ["PC", "PlayStation", "Xbox"],
    developer: "Saber Interactive",
    publisher: "Focus Entertainment",
    releaseDate: new Date("2020-04-28"),
    imageURL: "/images/snowrunner.png",
    isReleased: true,
  },
  {
    gameName: "Marvel’s Spider-Man 2",
    price: 4499,
    rating: { value: 4.9, count: 45000 },
    description:
      "Dual Spider-Men story featuring Peter Parker and Miles Morales defending NYC from Venom and other threats. Expanded web-swinging mechanics and larger playable area.",
    genres: ["Action-Adventure", "Superhero"],
    platforms: ["PlayStation"],
    developer: "Insomniac Games",
    publisher: "Sony Interactive Entertainment",
    releaseDate: new Date("2023-10-20"),
    imageURL: "/images/spider-man-2.png",
    isReleased: true,
  },
  {
    gameName: "TankHead",
    price: 999,
    rating: { value: 4.0, count: 2500 },
    description:
      "Fast-paced mech combat with fully customizable war machines. Engage in arena battles with destructible environments and modular weapon systems.",
    genres: ["Action", "Simulation"],
    platforms: ["PC", "Xbox"],
    developer: "MechaWorks Studio",
    publisher: "Indie Arcade",
    releaseDate: new Date("2024-09-05"),
    imageURL: "/images/tankhead.png",
    isReleased: false,
  },
  {
    gameName: "Torque Drift 2",
    price: 1499,
    rating: { value: 4.3, count: 9800 },
    description:
      "Competitive online drifting with realistic tire physics and livery customization. Features live multiplayer events and ghost challenge modes.",
    genres: ["Racing", "Sports"],
    platforms: ["PC", "PlayStation"],
    developer: "Grease Monkey Games",
    publisher: "Grease Monkey Games",
    releaseDate: new Date("2024-06-15"),
    imageURL: "/images/torque-drift-2.jpg",
    isReleased: false,
  },
];

export default games;
